apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-lightblue-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-lightblue-deployment
        image: index.docker.io/rocketronald/lightbluecompute-web
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: web-lightblue-service
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
   - port: 8081
     targetPort: 8081
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: web
  name: web-lightblue-service
spec:
  port:
    targetPort: 8081
  to:
    kind: Service
    name: web-lightblue-service
    weight: 100
