apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nodejs-sonarqube-task
spec:
#  --new v1beta1 style --
  resources:
    inputs:
      - {type: git, name: source}
  params:
    - default: 'node:12-stretch'
      name: node-image
      type: string
  steps:
    - args:
        - '-c'
        - |
          set -e
          if [ -n "${SONARQUBE_URL}" ]; then
              npm run sonarqube:scan --if-present
          else 
              echo "Skipping Sonar Qube step"
          fi
      command:
        - /bin/bash
      env:
        - name: SONARQUBE_URL
          valueFrom:
            configMapKeyRef:
              key: SONARQUBE_URL
              name: sonarqube-config
              optional: true
        - name: SONARQUBE_USER
          valueFrom:
            secretKeyRef:
              key: SONARQUBE_USER
              name: sonarqube-access
              optional: true
        - name: SONARQUBE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SONARQUBE_PASSWORD
              name: sonarqube-access
              optional: true
      image: $(inputs.params.node-image)
      name: sonarqube
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: .m2/repository
          name: m2-repository
      workingDir: /workspace/source
  volumes:
    - emptyDir: {}
      name: m2-repository
