apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-lightblue-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: "image-registry.openshift-image-registry.svc:5000/openshift/mysql"
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 20
          periodSeconds: 60
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Pass4Admin123"
        - name: MYSQL_USER
          value: "dbuser"
        - name: MYSQL_PASSWORD
          value: "Pass4dbUs3R"
        - name: MYSQL_DATABASE
          value: "inventorydb"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-lightblue-service
  labels:
    app: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
   - protocol: TCP
     port: 3306
     nodePort: 30006
